version: '3.8'

services:
  backend:
    build: .
    expose:
      - "8000"
    command: gunicorn --bind 0.0.0.0:8000 mateirobescu.wsgi:application
    env_file:
      - .env
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
