version: '3.8'

services:
  backend:
    build: .
    expose:
      - "8000"
    command: gunicorn --bind 0.0.0.0:8000 mateirobescu.wsgi:application
    env_file:
      - .env
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443" # Prepare the port
    volumes:
      # Add these two lines so Nginx can read certificates
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - backend
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot

volumes:
  certbot_conf:
  certbot_www: