# Generated by Django 5.2.4 on 2025-09-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='name_lower',
            field=models.CharField(default='a', editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
