# Generated by Django 5.2.4 on 2025-09-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_stack_name_lower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='name_lower',
        ),
    ]
