# Generated by Django 5.2.4 on 2025-09-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_stack_name_lower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stack',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='stack',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
