# Generated by Django 5.2.4 on 2025-09-21 18:39

import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_stack_options_stack_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=portfolio.models.project_image_path)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='stack',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stack',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='ProjectStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.stack')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('project', 'stack')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='stacks',
            field=models.ManyToManyField(through='portfolio.ProjectStack', to='portfolio.stack'),
        ),
    ]
