# Generated by Django 5.2.4 on 2025-09-22 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_alter_stack_name_alter_stack_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stacks',
            field=models.ManyToManyField(related_name='projects', through='portfolio.ProjectStack', to='portfolio.stack'),
        ),
        migrations.AlterField(
            model_name='projectstack',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_stacks', to='portfolio.project'),
        ),
        migrations.AlterField(
            model_name='projectstack',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_stacks', to='portfolio.stack'),
        ),
    ]
