# Generated by Django 5.2.4 on 2025-09-22 15:18

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_stacks_alter_projectstack_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to=portfolio.models.project_image_path),
            preserve_default=False,
        ),
    ]
