# Generated by Django 5.2.4 on 2025-09-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
