# Generated by Django 5.2.4 on 2025-10-16 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='is_filterable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stack',
            name='iconColor',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g., #1a2b3c)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
