# Generated by Django 5.2.4 on 2025-10-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_stack_is_filterable_alter_stack_iconcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='recaptcha_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
