# Generated by Django 5.2.4 on 2026-01-04 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_emaillog_recaptcha_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('title_en', models.CharField(blank=True, max_length=50, null=True)),
                ('title_ro', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=50)),
                ('subtitle_en', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle_ro', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('start_date_en', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date_ro', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('end_date_en', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date_ro', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('location_en', models.CharField(blank=True, max_length=50, null=True)),
                ('location_ro', models.CharField(blank=True, max_length=50, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CvSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ro', models.CharField(max_length=100, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_ro', models.TextField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cv_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='portfolio.cvitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='cvitem',
            name='cv_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolio.cvsection'),
        ),
    ]
