# Generated by Django 5.2.4 on 2026-01-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_cvitem_cvsection_bulletpoint_cvitem_cv_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cvitem',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cvitem',
            name='subtitle_ro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cvitem',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cvitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cvitem',
            name='title_ro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
