# Generated by Django 5.2.4 on 2026-01-04 22:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_cvitem_subtitle_alter_cvitem_subtitle_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV PDF',
                'verbose_name_plural': 'CV PDF',
            },
        ),
    ]
