# Generated by Django 5.2.4 on 2026-01-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_cvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
