# Generated by Django 5.2.4 on 2026-01-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_stack_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='hide',
        ),
        migrations.AddField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
